name: e_commerce_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.1.2
  flutter_dash: ^1.0.0
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.6
  persistent_bottom_nav_bar_v2: ^4.2.8
  readmore: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  