// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgbCRV3lhQ7SY_xyFwfQS46mYwKRxJ1oM',
    appId: '1:73800015734:web:e9bf46f65b4b714f8ee457',
    messagingSenderId: '73800015734',
    projectId: 'e-commerce-beb45',
    authDomain: 'e-commerce-beb45.firebaseapp.com',
    storageBucket: 'e-commerce-beb45.appspot.com',
    measurementId: 'G-SFVZ0F3009',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE1zWbtqPjvttt-pFdr1zpUzlRk9IoT1c',
    appId: '1:73800015734:android:88594048d74ae00a8ee457',
    messagingSenderId: '73800015734',
    projectId: 'e-commerce-beb45',
    storageBucket: 'e-commerce-beb45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLkK082_H0tLO8S7QFFyM_yZuFRo_xskg',
    appId: '1:73800015734:ios:0c5b26e764d012f78ee457',
    messagingSenderId: '73800015734',
    projectId: 'e-commerce-beb45',
    storageBucket: 'e-commerce-beb45.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLkK082_H0tLO8S7QFFyM_yZuFRo_xskg',
    appId: '1:73800015734:ios:cb4825654861ea768ee457',
    messagingSenderId: '73800015734',
    projectId: 'e-commerce-beb45',
    storageBucket: 'e-commerce-beb45.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
